### PR TITLE
new examples

### PR DESCRIPTION
**Pull request by ghost**
examples for SES added

### CODE REVIEW

**Comment by chilts** [comment]
Hi Joey,

Pulled, rebuilt and pushed. :)

Cheers,
Andy

**Comment by techtribe** [comment]
great! will be trying to do one service a day…but will be slower with services I don't know. Am trying to execute the items by myself first…to check for errors.

hope you have some time to provide feedback about my styling point yesterday. I understand if your still busy over there, otherwise point me to it…maybe I can help…like with the adding of general examples to the main service/endpoint pages to show a list of examples to explain how you could use a service for a (simple) task.

hy & thnx!

:)  

JOEY VAN DIJK
Sr. Flash Developer
joey@techtribe.nl (mailto:joey@techtribe.nl)
+31 (0) 6 30 40 36 86

Prins Hendriklaan 29
1075 AZ Amsterdam
www.techtribe.nl (http://www.techtribe.nl/)

**Comment by chilts** [comment]
Hi Joey,

Yep ok, will write an email in a couple of hours. It all looks fine to be honest ... all I'd do is move a bit of whitespace around. Maybe just make things a bit more consistent. Nothing major.

Chat to you soon.

Cheers,
Andy

P.S. In other news AwsSum has been nominated in the "Open Source Software Project" category of the New Zealand Open Source Awards for 2012 - http://www.nzosa.org.nz/ - finalists to be announced in a few days (not that I expect AwsSum will get in the finals, but you never know). :)

**Comment by techtribe** [comment]
Cool, saw it in your twitter and also the jump in amount of downloads. Hope the docs will help the coming months to make it even bigger. As an Actionscript developer (and now javascript again) I find it interesting that Node.JS is getting more and more growth as I also see it being mentioned more in the "old" Actionscript community.
Good times to follow, I hope. :)

And no rush!, just checking your planning ;)

Have a nice evening…will start my morning here ;)  

JOEY VAN DIJK
Sr. Flash Developer
joey@techtribe.nl (mailto:joey@techtribe.nl)
+31 (0) 6 30 40 36 86

Prins Hendriklaan 29
1075 AZ Amsterdam
www.techtribe.nl (http://www.techtribe.nl/)

**Comment by chilts** [comment]
Hi Joey,

I did some fairly minor modifications to some of your examples. Just
some whitespace here and there and just some small bits of extra text.
I put a few long param lines into a separate variable prior to the
call too - but just use your judgement on that. :)

Have a look at this commit to see the diffs:
- https://github.com/appsattic/node-awssum/commit/b5bccfd23879a839457cc57a477170762464eb87

Other than that, it's all really good! :) I am very much indebted to you!

Cheers,
Andy

On 23 October 2012 19:42, Techtribe notifications@github.com wrote:

> Cool, saw it in your twitter and also the jump in amount of downloads. Hope the docs will help the coming months to make it even bigger. As an Actionscript developer (and now javascript again) I find it interesting that Node.JS is getting more and more growth as I also see it being mentioned more in the "old" Actionscript community.
> Good times to follow, I hope. :)
> 
> And no rush!, just checking your planning ;)
> 
> Have a nice evening…will start my morning here ;)
> 
> JOEY VAN DIJK
> Sr. Flash Developer
> joey@techtribe.nl (mailto:joey@techtribe.nl)
> +31 (0) 6 30 40 36 86
> 
> Prins Hendriklaan 29
> 1075 AZ Amsterdam
> www.techtribe.nl (http://www.techtribe.nl/)
> 
> On Tuesday, October 23, 2012 at 8:38 AM, Andrew Chilton wrote:
> 
> > Hi Joey,
> > Yep ok, will write an email in a couple of hours. It all looks fine to be honest ... all I'd do is move a bit of whitespace around. Maybe just make things a bit more consistent. Nothing major.
> > Chat to you soon.
> > Cheers,
> > Andy
> > P.S. In other news AwsSum has been nominated in the "Open Source Software Project" category of the New Zealand Open Source Awards for 2012 - http://www.nzosa.org.nz/ - finalists to be announced in a few days (not that I expect AwsSum will get in the finals, but you never know). :)
> > 
> > —
> > Reply to this email directly or view it on GitHub (https://github.com/appsattic/node-awssum/pull/96#issuecomment-9692007).
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Andrew Chilton
e: chilts@appsattic.com
w: http://appsattic.com/
t: https://twitter.com/andychilton
p: +64 21 891 681

**Comment by techtribe** [comment]
Great, will follow these tweaks in the next batch of examples.

But why are you adding "," at the last item of an object? My javascript compilers are warning me about them.

hy

:)

PS: coming days will have to end a project so probably monday more examples.  

JOEY VAN DIJK
Sr. Flash Developer
joey@techtribe.nl (mailto:joey@techtribe.nl)
+31 (0) 6 30 40 36 86

Prins Hendriklaan 29
1075 AZ Amsterdam
www.techtribe.nl (http://www.techtribe.nl/)

**Comment by chilts** [comment]
Hi Joey,

On 24 October 2012 18:58, Techtribe notifications@github.com wrote:

> But why are you adding "," at the last item of an object? My javascript compilers are warning me about them.

I'm used to doing it with Perl and JavaScript doesn't care (compilers only warn against it because of Internet Exploder). In ES5 it's allowed. I even turn off checking of the trailing comma for AwsSum in jshint.

The main reason I do it is because if you add a new option into the object on a new line, you don't need to edit the line above to add a comma on the end. :) I don't think it matters too much and am happy to take it out - debating coding style isn't too important here - I guess I shouldn't have put them in but my fingers made me do it!!! :)

Cheers,
Andy

**Comment by techtribe** [comment]
fine, then I understand…found it awkward at first, but will try to add them myself.

just curious and thanks for the update.

JOEY VAN DIJK
Sr. Flash Developer
joey@techtribe.nl (mailto:joey@techtribe.nl)
+31 (0) 6 30 40 36 86

Prins Hendriklaan 29
1075 AZ Amsterdam
www.techtribe.nl (http://www.techtribe.nl/)

**Pull request merged**
