### PR TITLE
new examples

### PR DESCRIPTION
**Pull request by ghost**
examples to use with SimpleDB

### CODE REVIEW

**Comment by chilts** [comment]
As always, thanks Joey! :)

Got an interesting problem at the moment trying to figure out how to force AwsSum to check the SSL certs from AWS. :) My mate put me on to this : https://crypto.stanford.edu/~dabo/pubs/abstracts/ssl-client-bugs.html

Anyway, trying to see if I can get a patch in before v0.12. :)

Cheers,
Andy

**Comment by techtribe** [comment]
Finding SSL stuff hard to grasp at times but good luck with that! sorry :p But have seen the SSL-issue coming by, but was expecting more information from AWS. Strange.

Ending my big ass project so have some more time in the mornings to fix some examples, but I was also wondering if you have ever done something with multipart upload on S3? I am seeing a lot of blog posts about the wish to have something multi threaded fast to upload 200 GB+ to S3 for example. I have played with Actionscript to build an uploader tool and found it interesting to split the file up and multipart upload it.  
But I was wondering if you played / optimized such a scenario for a server-upload use-case? Or do you have any tips, because I will fix the examples, but in the mean time (as a hobby project) will have a look how well Node JS with node-awssum can provide me with a tool to easily upload files/folders to S3 and later to Amazon Glacier.

Any tips are welcome & I will keep you posted.

Thnx!

:D  

JOEY VAN DIJK
Sr. Flash Developer
joey@techtribe.nl (mailto:joey@techtribe.nl)
+31 (0) 6 30 40 36 86

Prins Hendriklaan 29
1075 AZ Amsterdam
www.techtribe.nl (http://www.techtribe.nl/)

**Comment by techtribe** [comment]
and….just mention your issues, maybe I will have time/experience to help out. Cannot always answer yes, but will have a look at it.

;)  

JOEY VAN DIJK
Sr. Flash Developer
joey@techtribe.nl (mailto:joey@techtribe.nl)
+31 (0) 6 30 40 36 86

Prins Hendriklaan 29
1075 AZ Amsterdam
www.techtribe.nl (http://www.techtribe.nl/)

**Comment by chilts** [comment]
Hi Joey,

Yeah, I think I have the start of a plan forming for the ca.crt stuff. I think I can pass an option to the https.request() method to check the certs against a file.

Anyway, on to multipart - there is an integration test for it, so take a look here:
- https://github.com/appsattic/node-awssum/blob/master/test/integration/amazon-s3-multipart.js

Hope that helps. :) Multipart support in AwsSum should be 100% working so let me know if you find any problems.

Cheers,
Andy

**Comment by techtribe** [comment]
Sure, thnx!  

:D  

JOEY VAN DIJK
Sr. Flash Developer
joey@techtribe.nl (mailto:joey@techtribe.nl)
+31 (0) 6 30 40 36 86

Prins Hendriklaan 29
1075 AZ Amsterdam
www.techtribe.nl (http://www.techtribe.nl/)

**Comment by chilts** [comment]
Just added a GetAttributes example and some example results. :)

Cheers,
Andy

**Comment by techtribe** [comment]
Nice, but what do you expect now? i think we need to align all examples, so add (no) result response?

hy

:)  

JOEY VAN DIJK
Sr. Flash Developer
joey@techtribe.nl (mailto:joey@techtribe.nl)
+31 (0) 6 30 40 36 86

Prins Hendriklaan 29
1075 AZ Amsterdam
www.techtribe.nl (http://www.techtribe.nl/)

**Comment by chilts** [comment]
Hi Joey,

Yes we could to but I don't think it is critical that everything has one. I'd rather carry on adding examples of how to use each operation more than what the results look like.

The most important thing is to have the examples exactly as you are doing. I think having a result on _some_ examples makes sense (e.g. the GetAttributes operation) but many of the other results are very similar.

For the moment, don't worry about it unless you want to. :) As I say, the most important thing are the examples themselves. And for that you're already doing great service!

Cheers,
Andy

**Comment by techtribe** [comment]
Ok, fine then I know how to proceed.

;)  

JOEY VAN DIJK
Sr. Flash Developer
joey@techtribe.nl (mailto:joey@techtribe.nl)
+31 (0) 6 30 40 36 86

Prins Hendriklaan 29
1075 AZ Amsterdam
www.techtribe.nl (http://www.techtribe.nl/)

**Pull request merged**
