### PR TITLE
new examples

### PR DESCRIPTION
**Pull request by ghost**
added IMD / SQS examples, will proceed later with SQS

### CODE REVIEW

**Comment by chilts** [comment]
Thanks, as always. :)

**Comment by techtribe** [comment]
you're welcome! ;)

**Comment by techtribe** [comment]
Andrew,

am I right that my SQS-examples did not propagate to awssum.io? I thought it was Github Pages you were using or are you uploading manually?

just curious.

hy

:D  

JOEY VAN DIJK
Sr. Flash Developer
joey@techtribe.nl (mailto:joey@techtribe.nl)
+31 (0) 6 30 40 36 86

Prins Hendriklaan 29
1075 AZ Amsterdam
www.techtribe.nl (http://www.techtribe.nl/)

**Comment by chilts** [comment]
Heh, you are totally right! I pushed patch but didn't regenerate the docs. My bad.

I've just pushed, so you can either hard refresh the pages you want, or it'll come good in an hour or so (they get built within a few mins but I think GitHub pages puts an hour cache on them).

Cheers,
Andy

**Comment by techtribe** [comment]
thnx for the input, just checking/curious. ;)

JOEY VAN DIJK
Sr. Flash Developer
joey@techtribe.nl (mailto:joey@techtribe.nl)
+31 (0) 6 30 40 36 86

Prins Hendriklaan 29
1075 AZ Amsterdam
www.techtribe.nl (http://www.techtribe.nl/)

**Pull request merged**
