### PR TITLE
Fixed typo in cloudwatch api.

### PR DESCRIPTION
**Pull request by garrows**
StateValeu changed to StateValue

### CODE REVIEW

**Comment by chilts** [comment]
Hi Glen,

Thanks for that! :) As always, little things like this make the library better for everyone ... much appreciated.

Cheers,
Andy

**Comment by garrows** [comment]
No worries. Thanks for the great library. 

I might start expanding on some of your examples code too.

**Comment by chilts** [comment]
Hey Glen,

That'd be awesome - thanks!

/cc @Techtribe

Joey van Dijk has been doing a great job of sending me lots of pull requests for the documentation site. It's sitting at http://awssum.io/ if you haven't seen it and is built from the gh-pages branch of this repo. Might be worth saying hello to him.

:)

Andy

**Comment by garrows** [comment]
Cool. I'll be committing there for sure.

**Pull request merged**
