### PR TITLE
Fix Ex2.CreateTags

### PR DESCRIPTION
**Pull request by mikefleming**
With args {'ResourceId': ['i-instance], 'Tag': {'Key': ['Name'], 'Value': ['myname']}}

...I get a 200 back from Amazon.

### CODE REVIEW

**Comment by chilts** [comment]
Hi Mike,

Brilliant, thanks for the fix! :) I love getting pull requests. Instead though I've actually fetched your commit (df2a069) individually so that there aren't the extra merge commits.

I've also looked into the problem a little bit deeper. What you had didn't actually change anything since 'paramData' was defined just as we had it at the top ... except I'd set required to be false instead of true (sad mistake on my part).

Anyway, I've fixed that bug ... but wait, there's more.

As I said, your fix didn't actually change anything but instead I found a bug in awssum.js:addParamData() and changed a number of things in there as well as another related function! :)

So, I think we've found and fixed two bugs together from your initial PR.

Many thanks!

Cheers,
Andy

**Comment by mikefleming** [comment]
Oh excellent!

Yeah, I figured the fix I sent you wasn't the best one, but I couldn't
quite figure out what the best one was.

Thanks very much!

By the way, I'm considering adding a bunch for Amazon's Elastic Mapreduce
API. Do you know if someone is working on this already? Any pointers on how
to do it right? (Other than look at others I suppose :)

Mike

On Sat, Aug 4, 2012 at 2:23 AM, Andrew Chilton <
reply@reply.github.com

**Comment by chilts** [comment]
Hi Mike,

You're in luck as of 2 days ago:
- https://github.com/appsattic/node-awssum/blob/master/lib/amazon/emr.js
- https://github.com/appsattic/node-awssum/blob/master/lib/amazon/emr-config.js

Have fun! :)

Cheers,
Andy

**Comment by mikefleming** [comment]
Hey excellent! Thanks!

Mike

On Mon, Aug 6, 2012 at 12:33 PM, Andrew Chilton <
reply@reply.github.com

**Pull request closed without merging**
