### PR TITLE
Updated api version so WaitTimeSeconds works

### PR DESCRIPTION
**Pull request by garrows**
Updated api version so WaitTimeSeconds works.

### CODE REVIEW

**Comment by garrows** [comment]
Hurry up @chilts, its been 4 minutes. You've usually done this within 30 seconds. :P

**Comment by chilts** [comment]
Heh, Hi Glen :)

Sorry, didn't log on last night and only saw it on the train this morning. I noticed there are a lot of changes in the patch you sent me ...

So I'm not going to pull the whole thing, but will just cherry-pick 3ec982e5c86e6651f309f19569fd2316a8de692b. I need to go through the other bits and see what is going on - it looks like a merge so I probably don't need to pull it. :)

In the future, the best practise is to keep your master as pristine and just track it with my master, then for each pull request, create a branch from that with the one or two commits as fixes and then ask me to pull that branch. It'll make things easier each time I see a pull request to figure out what has or hasn't changed.

Ok, that one commit has been cherry picked and pushed. I'll close this PR though without merging - don't be alarmed. :-p

Cheers,
Andy

**Comment by chilts** [comment]
And thanks. :)

**Comment by garrows** [comment]
Whoa! I dont know what happened but I didnt meant to submit all those other changes. All I wanted to change was the SQS version number. I must have somehow reverted some old changes or something. 

That will teach me for not doing a diff first.

**Comment by chilts** [comment]
Hehe. No worries. Easily fix by just keeping a pristine master which tracks mine. :)

Mind if I send you a private email (email on your profile ok?) ... usually I just like to know what people are using AwsSum for so I can focus on those parts more.

Cheers,
Andy

**Comment by garrows** [comment]
Yeah. My bad. 

Of course you can email me. glen.arrowsmith@gmail.com

**Pull request closed without merging**
