### PR TITLE
Added Sydney to STS

### PR DESCRIPTION
**Pull request by garrows**
Added Sydney to STS. This actually makes Sydney for Dynamo (and anything else that uses STS work) instead of crashing.

### CODE REVIEW

**Comment by chilts** [comment]
Hi Glen,

Thanks ... I've just cherry-picked the last commit again. I always forget about STS when there is a new region. :)

Cheers,
Andy

**Comment by garrows** [comment]
Thanks Andy. What do you mean cherry-picked? There is only one file this time.

**Comment by chilts** [comment]
See above here, there are 5 commits. A merge, your WaitTimeSeconds commit, two more merges and then your change. So I ran:

$ git cherry-pick 04a7b53

just so I got your last commit only.

Not sure if I mentioned but if you keep your master just tracking mine and don't do any changes on it, it makes things easier. Just do rebase on your master rather than merge since again, it keeps history cleaner.

e.g. Whilst on your master: git rebase appsattic/master # assuming you've set up your appsattic remote as this repo

Then, when you want to change anything, create a branch, commit there and then push your branch to your repo, then ask for the pull request.

This means you don't need to merge my stuff into your master, you just rebase your master on top of mine. And then each branch with each change is just the relevant one or two commits for the fix.

I hope that makes sense. Sorry if it's a bit long winded but that's probably the best way to stay sane. :)

Cheers,
Andy

**Comment by pilsy** [comment]
Any chance you could release this chilts? really need that endpoint in our code

**Comment by chilts** [comment]
I'll give it a go later on today.

**Pull request closed without merging**
